### PR TITLE
docs: improve `operationInaccessible` event

### PR DESCRIPTION
**Pull request by josepot**
cc @tomaka

### CODE REVIEW

**Comment by tomaka** [comment]
No, the sentence is correct, I don't see why you think that this event is specific to storage

**Comment by josepot** [comment]
> No, the sentence is correct, I don't see why you think that this event is specific to storage

Because the next sentence states that:

> The `operationInaccessible` event is produced if the JSON-RPC server was incapable of obtaining the storage items necessary for the given operation.

**Comment by josepot** [comment]
I'm guessing that the other operation that can also trigger this event must be [`chainHead_unstable_body`](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_body.html#chainhead_unstable_body), since it's probably just sugar for accessing the storage entry of `System.ExtrinsicData`? If that's the case, I'm starting to think that we should probably remove `chainHead_unstable_body` from the API.

**Comment by tomaka** [comment]
You're overthinking it, and it's just the next sentence that must mention that it can happen if failing to retrieve the body.

> I'm guessing that the other operation that can also trigger this event must be [chainHead_unstable_body](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_body.html#chainhead_unstable_body), since it's probably just sugar for accessing the storage entry of System.ExtrinsicData? If that's the case, I'm starting to think that we should probably remove chainHead_unstable_body from the API.

It's not just sugar. If anything, it's `System.ExtrinsicData` that should be removed.

> Ahhh, wait, of course: [chainHead_unstable_call](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_call.html#chainhead_unstable_call) also requires from a storage access to :code, so I guess that if the storage read is failing, then it will also trigger this event... I see 🤔

`call` reads the storage from the network because doing a runtime call accesses the storage.

**Pull request closed without merging**
